# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

AreaOfInterest.create(name: "Child Advocacy  (Adoption, and Foster Care)", interest_type: "Charity")
AreaOfInterest.create(name: "Un-Born Child Advocacy (Abortion)", interest_type: "Charity")
AreaOfInterest.create(name: "Legislative Advocacy", interest_type: "Charity")
AreaOfInterest.create(name: "Prison Ministry", interest_type: "Charity")
AreaOfInterest.create(name: "Community Events and Advocacy", interest_type: "Charity")
AreaOfInterest.create(name: "Homeless/Transitional Housing", interest_type: "Charity")
AreaOfInterest.create(name: "Family Advocacy", interest_type: "Charity")
AreaOfInterest.create(name: "Aging Population Advocacy", interest_type: "Charity")
AreaOfInterest.create(name: "Marketplace Ministry", interest_type: "Charity")
AreaOfInterest.create(name: "Veterans Support", interest_type: "Charity")
AreaOfInterest.create(name: "Sex Traffic and Prostitution", interest_type: "Charity")
AreaOfInterest.create(name: "Feeding the Hungry", interest_type: "Charity")
AreaOfInterest.create(name: "Discipleship", interest_type: "Charity")
AreaOfInterest.create(name: "Mentoring (K-12)", interest_type: "Charity")
AreaOfInterest.create(name: "Mentoring (Adult)", interest_type: "Charity")
AreaOfInterest.create(name: "Training", interest_type: "Charity")
AreaOfInterest.create(name: "Medical Missions", interest_type: "Charity")
AreaOfInterest.create(name: "Media Ministry", interest_type: "Charity")
AreaOfInterest.create(name: "Missions - Outside US", interest_type: "Charity")

AreaOfInterest.create(name: "Agriculture", interest_type: "Vendor")
AreaOfInterest.create(name: "Energy", interest_type: "Vendor")
AreaOfInterest.create(name: "Food", interest_type: "Vendor")
AreaOfInterest.create(name: "Housing", interest_type: "Vendor")
AreaOfInterest.create(name: "Sanitation", interest_type: "Vendor")
AreaOfInterest.create(name: "Water", interest_type: "Vendor")


CampaignCategory.create(name: "Animals")
CampaignCategory.create(name: "Faith")
CampaignCategory.create(name: "Medical")
CampaignCategory.create(name: "Community")
CampaignCategory.create(name: "Family")
CampaignCategory.create(name: "Competitions")
CampaignCategory.create(name: "Events")
CampaignCategory.create(name: "Memorials")
CampaignCategory.create(name: "Sports")
CampaignCategory.create(name: "Education")
CampaignCategory.create(name: "Charity")
CampaignCategory.create(name: "Creative")
CampaignCategory.create(name: "Travel")
CampaignCategory.create(name: "Wishes")
CampaignCategory.create(name: "Other")

ProductCategory.create(name: "Agriculture")
ProductCategory.create(name: "Energy")
ProductCategory.create(name: "Food")
ProductCategory.create(name: "Housing")
ProductCategory.create(name: "Sanitation")
ProductCategory.create(name: "Water")
#
# Region.create(name: "Charleston", lonlat: "0101000020E6100000C4D155BABBFB53C05470784144644040")
# Region.create(name: "Greenville", lonlat: "0101000020E6100000B3B112F3AC9854C0D7A6B1BD166C4140")
# Region.create(name: "Columbia", lonlat: "0101000020E6100000E99C9FE2384254C086E8103812004140")
# Region.create(name: "Spartanburg", lonlat: "0101000020E61000008FC2F5285C7B54C0E9995E622C794140")
AdminUser.create!(email: 'admin@commitgood.com', password: 'Commit@!23', password_confirmation: 'Commit@!23')